// Copyright (c) 2021 Sultim Tsyrendashiev
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#version 460

#define DESC_SET_FRAMEBUFFERS 0
#define DESC_SET_GLOBAL_UNIFORM 1
#define DESC_SET_TONEMAPPING 2
#include "ShaderCommonGLSLFunc.h"
#include "Exposure.h"

layout(local_size_x = COMPUTE_BLOOM_DOWNSAMPLE_GROUP_SIZE_X, local_size_y = COMPUTE_BLOOM_DOWNSAMPLE_GROUP_SIZE_Y, local_size_z = 1) in;

vec3 getBloomInput( const vec3 hdr, const vec3 screenEmis )
{
    float evBloom = getCurrentEV100() + globalUniform.bloomEmissionMultiplier;

    vec3 bloom = ( hdr + screenEmis * ev100ToLuminance( evBloom ) ) *
                 ev100ToLuminousExposure( getCurrentEV100() );

    if( any( isnan( bloom ) ) || any( isinf( bloom ) ) )
    {
        bloom = vec3( 0 );
    }

    return bloom * smoothstep( 0,
                               globalUniform.bloomThreshold,
                               getLuminance( bloom ) );
}


void main()
{
    const ivec2 fullResPix = ivec2( gl_GlobalInvocationID ) * 2 + 1;
    if( fullResPix.x >= int( globalUniform.renderWidth ) ||
        fullResPix.y >= int( globalUniform.renderHeight ) )
    {
        return;
    }

    vec3       hdr        = texelFetch( framebufFinal_Sampler, fullResPix, 0 ).rgb;
    const vec3 screenEmis = texelFetch( framebufScreenEmission_Sampler, fullResPix, 0 ).rgb;

    {
        vec4 volumetric = texelFetch( framebufScattering_Sampler, fullResPix, 0 );
        hdr             = hdr * volumetric.a + volumetric.rgb;
    }

    imageStore( framebufBloomInput, ivec2( gl_GlobalInvocationID ), vec4( getBloomInput( hdr, screenEmis ), 0.0 ) );
}
