#version 460

#define DESC_SET_FRAMEBUFFERS 0
#define DESC_SET_GLOBAL_UNIFORM 1
#include "ShaderCommonGLSLFunc.h"

layout(local_size_x = COMPUTE_COMPOSE_GROUP_SIZE_X, local_size_y = COMPUTE_COMPOSE_GROUP_SIZE_Y, local_size_z = 1) in;

void main()
{
    const ivec2 pix = ivec2( gl_GlobalInvocationID.x, gl_GlobalInvocationID.y );

    if( pix.x >= uint( globalUniform.renderWidth ) || pix.y >= uint( globalUniform.renderHeight ) )
    {
        return;
    }

    vec3 hdr  = texelFetch( framebufPreFinal_Sampler, pix, 0 ).rgb;
    vec3 emis = texelFetch( framebufScreenEmisRT_Sampler, pix, 0 ).rgb;
    vec3 fog  = texelFetch( framebufAcidFogRT_Sampler, pix, 0 ).rgb;

    imageStore( framebufFinal, pix, vec4( hdr, 0 ) );
    imageStore( framebufScreenEmission, pix, vec4( emis, 0 ) );
    imageStore( framebufAcidFog, pix, vec4( fog, 0 ) );
}